[tool.poetry]
name = "genetic-algorithm"
version = "0.1.0"
description = ""
authors = ["Kuba Podkom√≥rka <jpodkomorka19@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
